#!/bin/bash
set -ex

container=$(buildah from docker.io/library/debian:12)

buildah config \
    --label "org.opencontainers.image.source=$SOURCE" \
    --label "org.opencontainers.image.authors=$AUTHORS" \
    --label "org.opencontainers.image.description=$DESCRIPTION" \
    $container

buildah run "$container" bash -exc "$(cat run)"
buildah commit --format docker "$container" working-image

buildah tag working-image "$IMAGE:$TAG"
