#!/bin/bash
set -ex

container=$(buildah from scratch)

buildah unshare
mountpoint=$(buildah mount "$container")

debootstrap --force-check-gpg \
    --variant=minbase \
    --include=bash,wget \
    bookworm \
    "$mountpoint"

buildah config \
    --label "org.opencontainers.image.source=$SOURCE" \
    --label "org.opencontainers.image.authors=$AUTHORS" \
    --label "org.opencontainers.image.description=$DESCRIPTION" \
    --env LANG=en_US.UTF-8 \
    --env LC_ALL=en_US.UTF-8 \
    "$container"

buildah run "$container" bash -exc "$(cat run)"
buildah commit --format docker "$container" working-image

buildah tag working-image "$IMAGE:$TAG"
