#!/bin/bash

container=$(buildah from docker.io/library/debian:12)

buildah config \
    --label description="here we go" \
    $container

buildah run "$container" bash -vc '
    export DEBIAN_FRONTEND=noninteractive
    apt-get -qq update
    apt-get -qqo Dpkg::Use-Pty=0 satisfy \
        wget
'

buildah commit --format docker "$container" gcr

buildah tag gcr ghcr.io/disputechalice/gcr:latest

buildah push gcr docker://ghcr.io/disputechalice/gcr:latest
