#!/bin/bash
set -ex

[[ -n $SOURCE ]]
[[ -n $AUTHORS ]]
[[ -n $DESCRIPTION ]]

container=$(buildah from scratch)

mountpoint=$(buildah mount "$container")

debootstrap --force-check-gpg \
    --variant=minbase \
    --include=tzdata,locales,bash,wget \
    bookworm \
    "$mountpoint"

buildah config \
    --label "org.opencontainers.image.source=$SOURCE" \
    --label "org.opencontainers.image.authors=$AUTHORS" \
    --label "org.opencontainers.image.description=$DESCRIPTION" \
    --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    --env LC_ALL=C.UTF-8 \
    --env LANG=C.UTF-8 \
    "$container"

buildah run "$container" bash -exc "$(cat run)"
buildah commit --format docker "$container" working-image

buildah tag working-image "$IMAGE:$TAG"
