#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
dpkg-reconfigure tzdata

# cat > /etc/locale.gen <<< "C.UTF-8 UTF-8"
# cat > /etc/default/locale <<< "C.UTF-8"
# dpkg-reconfigure locales

cat > /etc/apt/apt.conf.d/00no-recommends << EOF
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF
rm -vf /etc/apt/apt.conf.d/70debconf

apt-get -qq update
apt-get -qqo Dpkg::Use-Pty=0 satisfy \
    wget

apt-get clean
