#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
dpkg-reconfigure tzdata

cat > /etc/locale.gen <<< "C.UTF-8 UTF-8"
cat > /etc/default/locale <<< "C.UTF-8"
dpkg-reconfigure locales

cat > /etc/apt/apt.conf.d/00container << EOF

Dpkg::Use-Pty "0";

Binary::apt-get {
    quiet "2";
    APT::Install-Recommends "false";
    APT::Install-Suggests "false";
    APT::Keep-Downloaded-Packages "false";
}
EOF

rm -vf /etc/apt/apt.conf.d/70debconf

apt-get update
apt-get satisfy \
    wget dpkg-dev lintian

# apt-get clean

dpkg --purge apt

# rm -vrf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

groupadd -g 1000 worker
useradd --create-home --no-log-init -u 1000 -g 1000 worker
