name: Bug
description: "Experienced other than expected behaviour."
title: "brief & specific"
labels: ["bug"]
body:
  - type: checkboxes
    id: system
    attributes:
      label: "System(s):"
      description: "Issue experienced with install on:"
      options:
        - label: PVE
        - label: PBS
        - label: PMG
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: "Detailed version information from the system:"
      description: "Run the command below and paste its output here."
      placeholder: "apt list free-pmx-no-subscription proxmox-widget-toolkit pve-manager proxmox-backup-server pmg-gui"
      render: shell
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Version of the tool used. Check with `apt policy <package>`.
      options:
        - 0.3.0~pre2
        - 0.3.0~pre1
        - 0.2.0
        - other
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
