#!/bin/bash
set -e

[[ -n $IMAGE ]]
[[ -n $TAG ]]
[[ -n $SOURCE ]]
[[ -n $AUTHORS ]]
[[ -n $DESCRIPTION ]]

container=$(buildah from scratch)

mountpoint=$(buildah mount "$container")

mkdir "$mountpoint"/mnt
mount --bind builder "$mountpoint"/mnt

mkdir -p "$mountpoint"/dev/pts
mount -t devpts devpts "$mountpoint"/dev/pts -o gid=5,mode=666

debootstrap \
    --force-check-gpg \
    --variant=minbase \
    --include=tzdata,locales,bash \
    trixie \
    "$mountpoint"

buildah config \
    --env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    --env LC_ALL=C.UTF-8 \
    --env LANG=C.UTF-8 \
    "$container"

buildah run "$container" /mnt/run

buildah config \
    --user worker:worker \
    --label "org.opencontainers.image.source=$SOURCE" \
    --label "org.opencontainers.image.authors=$AUTHORS" \
    --label "org.opencontainers.image.description=$DESCRIPTION" \
    "$container"

buildah commit --format docker "$container" builder

buildah tag builder "$IMAGE:$TAG"
