#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
dpkg-reconfigure tzdata

cat > /etc/locale.gen <<< "C.UTF-8 UTF-8"
cat > /etc/default/locale <<< "C.UTF-8"
dpkg-reconfigure locales

rm -vf /etc/apt/apt.conf.d/*
cp /mnt/apt.conf /etc/apt/apt.conf

apt-get update
apt-get satisfy \
    wget \
    dpkg-dev \
    lintian

# apt-get clean

dpkg --purge apt

# rm -vrf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# groupadd -g 1000 worker
useradd --no-create-home --no-log-init -u 1001 worker
