#!/bin/bash
set -e

[[ -f /mnt/apt.conf ]]

export APT_CONFIG=/mnt/apt.conf
export DEBIAN_FRONTEND=noninteractive

ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
dpkg-reconfigure tzdata

rm -rf /usr/share/locale/*
cat > /etc/locale.gen <<< "C.UTF-8 UTF-8"
locale-gen
cat > /etc/default/locale <<< "C.UTF-8"

apt-get update
apt-get satisfy \
    wget

dpkg --purge apt

rm -rf /usr/share/{info,doc,man}

useradd --no-create-home --no-log-init -u 1001 worker
