#!/bin/bash
set -e

[[ -f /mnt/apt.conf ]]

export APT_CONFIG=/mnt/apt.conf
export DEBIAN_FRONTEND=noninteractive

ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
dpkg-reconfigure tzdata

cat > /etc/locale.gen <<< "C.UTF-8 UTF-8"
cat > /etc/default/locale <<< "C.UTF-8"
dpkg-reconfigure locales

apt-get update
apt-get satisfy \
    wget

dpkg --purge apt

ls -la /var/cache/apt/archives

useradd --no-create-home --no-log-init -u 1001 worker
