#!/bin/bash

init_apt() {
  rm -vf /etc/apt/apt.conf.d/*

  cat /etc/apt/apt.conf << EOF
Binary::apt-get {
    quiet "2";
    APT::Get::Assume-Yes "true";
    APT::Install-Recommends "false";
    APT::Install-Suggests "false";
    APT::Keep-Downloaded-Packages "false";
}

Dpkg::Options {
    "--force-confdef";
    "--force-confold";
};

Dpkg::Use-Pty "0";
EOF

  export DEBIAN_FRONTEND=noninteractive        
  apt-get update
}
