name: Build Push
on:
  workflow_dispatch:
jobs:
  build-push:
    env:
      SOURCE: ${{ github.event.repository.html_url }}
      IMAGE: ghcr.io/${{ github.repository }}:latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Append Source Label
        run: |
          cat >> Containerfile <<< \
          'LABEL org.opencontainers.image.source="'$SOURCE'"'

      - name: Build Image
        run: podman build . --tag ${{ env.IMAGE }}

      - name: Run Image
        run: podman run ${{ env.IMAGE }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Registry
        run: podman push ${{ env.IMAGE }}
