name: publish
on:
  push
jobs:
  publish-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/disputechalice/gcr:latest
          docker run ghcr.io/disputechalice/gcr:latest
          docker push ghcr.io/disputechalice/gcr:latest
          
