name: publish
on:
  workflow_dispatch:
jobs:
  publish-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build . --tag ghcr.io/disputechalice/gcr:latest
      - name: Run
        run: docker run ghcr.io/disputechalice/gcr:latest
      - name: Push
        run: docker push ghcr.io/disputechalice/gcr:latest
          
