name: Publish
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}
  TAG: latest
  SOURCE: ${{ github.event.repository.html_url }}
  AUTHORS: ${{ vars.AUTHORS }}
  DESCRIPTION: ${{ vars.DESCRIPTION }}

jobs:
  build-push:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          docker build . \
            --tag "$IMAGE:$TAG" \
            --label "org.opencontainers.image.source=$SOURCE" \
            --label "org.opencontainers.image.authors=$AUTHORS" \
            --label "org.opencontainers.image.description=$DESCRIPTION"

      - name: Run
        run: docker run "$IMAGE:$TAG"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Registry
        run: docker push "$IMAGE:$TAG"
