on:
  workflow_dispatch:
jobs:
  build-publish:
    env:
      SOURCE: ${{ github.event.repository.html_url }}
      IMAGE: ghcr.io/${{ github.repository }}:latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Add Image Source
        run: |
          cat >> Dockerfile <<< \
          'LABEL org.opencontainers.image.source="'$SOURCE'"'

      - name: Build
        run: docker build . --tag ${{ env.IMAGE }}

      - name: Run
        run: docker run ${{ env.IMAGE }}

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: docker push ${{ env.IMAGE }}
      
      - name: Dump github context
        env:
         GH: ${{ toJson(github) }}
        shell: bash
        run:   echo "$GH"
