name: Publish
on:
  workflow_dispatch:

env:
  CONTAINERFILE: Dockerfile
  IMAGE: ghcr.io/${{ github.repository }}
  TAG: latest
  DESCRIPTION: "Here we go..."  
  SOURCE: ${{ github.event.repository.html_url }}

jobs:
  build-push:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          podman build . \
            --tag "$IMAGE:$TAG" \
            --label "org.opencontainers.image.description=$DESCRIPTION" \
            --label "org.opencontainers.image.source $SOURCE"

      - name: Run
        run: podman run "$IMAGE:$TAG"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Registry
        run: podman push "$IMAGE:$TAG"
