name: publish
on:
  workflow_dispatch:
jobs:
  env:
    TAG: ghcr.io/disputechalice/gcr:v1
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build . --tag ${{ env.TAG }}
      - name: Run
        run: docker run ${{ env.TAG }}
      - name: Push
        run: docker push ${{ env.TAG }}
